### ISSUE TITLE
Running Tests Fails on import pyhit

### ISSUE THREAD

**Issue by jonesjp** [aladshaw3/dgosprey2#1]
This might be an issue with the latest version of Moose, but I followed these instructions for installing Moose on my Mac Mojave machine:
https://mooseframework.inl.gov/getting_started/installation/macos_mojave.html

After successfully installing Moose, I ran these commands:
```bash
$ git clone https://github.com/aladshaw3/dgosprey2.git
$ cd dgosprey2/
$ make -j10
...
18 warnings generated.
3 warnings generated.
1 warning generated.
23 warnings generated.
Linking Library /Users/.../dgosprey2/lib/libdgosprey-opt.la...
Linking Executable /Users/.../dgosprey2/dgosprey-opt...
$ ./run_tests -j4
Traceback (most recent call last):
  File "./run_tests", line 11, in <module>
    from TestHarness import TestHarness
  File "/Users/.../moose/python/TestHarness/__init__.py", line 10, in <module>
    from .TestHarness import TestHarness
  File "/Users/.../moose/python/TestHarness/TestHarness.py", line 17, in <module>
    from FactorySystem.Factory import Factory
  File "/Users/.../moose/python/FactorySystem/__init__.py", line 13, in <module>
    from .Parser import Parser
  File "/Users/.../moose/python/FactorySystem/Parser.py", line 17
    print('failed to import pyhit - try running "make hit" in the $MOOSE_DIR/test directory.', file=sys.stderr)
                                                                                                   ^
SyntaxError: invalid syntax
```

**Comment by aladshaw3** [comment]
Issue was caused by run_tests looking for the wrong version of python. This was caused by a legacy interface on my Mac machine that only had python2 available. Update should use whatever version of python you have. 

Update your local branch with the master branch to get the run_tests fix (run command "git pull"). Then, rebuild and run the  tests again. 

Note: On my new machine, some tests may fail with ExoDiff errors. This may be caused by changes in solver tolerances downstream. It is likely not an issue, but I may look into later.

**Comment by jonesjp** [comment]
Thank you so much! This fixed it.
